app: 
  mode: debug
  port: :8082
  url: "http://blog.iyunj.cn"
  name: 云静博客
  keywords: 云静,博客,TP6,Admin
  description: 用云静Admin TP6快速构建自己的应用
  version: 1.1.59
  author: 
    qq: 1071446619
    email: 1071446619@qq.com

database: 
  type: mysql
  host: 192.168.171.201
  port: 3306
  user: db_yunj_blog
  password: 123456
  name: db_yunj_blog
  table_prefix: yj_
  max_idle_conns: 10  # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量

redis:
  host: 192.168.171.201
  port: 6379
  db: 0
  password: "123456"
  prefix: "yj.blog:"  # 缓存key前缀
  max_idle: 30  # 连接池中最大的空闲连接数
  max_active: 30  # 连接池中最大的活动连接数
  idle_timeout: 200 # 空闲连接的超时时间

# 默认值
default:
  article:
    cover: "/static/blog/imgs/informal-essay.png" # 文章默认封面
  category: # 默认分类
    id: -1
    pid: 0
    name: "随笔"
    img: "/static/blog/imgs/informal-essay.png"

# 百度站点地图
baidu:
  site_map_site: "blog.iyunj.cn"
  site_map_token: "HpNxVryEdL51pRB7"

# Elasticsearch
elasticsearch:
  enable: true
  index_prefix: "blog_" # 索引前缀
  hosts: 
    - "http://192.168.171.201:9200"